services:
  dxa_api:
    build: .
    container_name: dxa_quality_control_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]